{
  "openapi": "3.0.1",
  "info": {
    "title": "API V1",
    "version": "v1"
  },
  "paths": {
    "/posts": {
      "get": {
        "summary": "list posts",
        "responses": {
          "200": {
            "description": "successful"
          }
        }
      },
      "post": {
        "summary": "create post",
        "responses": {
          "200": {
            "description": "successful"
          }
        }
      }
    },
    "/posts/{id}": {
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "description": "id",
          "required": true,
          "schema": {
            "type": "string"
          }
        }
      ],
      "get": {
        "summary": "show post",
        "responses": {
          "200": {
            "description": "successful"
          }
        }
      },
      "patch": {
        "summary": "update post",
        "responses": {
          "200": {
            "description": "successful"
          }
        }
      },
      "put": {
        "summary": "update post",
        "responses": {
          "200": {
            "description": "successful"
          }
        }
      },
      "delete": {
        "summary": "delete post",
        "responses": {
          "200": {
            "description": "successful"
          }
        }
      }
    }
  },
  "servers": [
    {
      "url": "http://{defaultHost}",
      "variables": {
        "defaultHost": {
          "default": "localhost:3000"
        }
      }
    }
  ]
}